Algoritmo "ENTRADA E SAIDA DE DADOS"
// Disciplina   : [ALGORITMO E LOGICA)
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : FELIPE DA SILVA QUEIROZ
// Data atual  : 21/09/2022
Var
// Seção de Declarações das variáveis
        nome; caracter
        nota; inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
       leia (nome)
       leia (nota)

Fimalgoritmo