Algoritmo "VARIAVEIS"
// Disciplina   : [ALGORITMO E LOGICA)
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : FELIPE DA SILVA QUEIROZ
// Data atual  : 21/09/2022
Var
// Seção de Declarações das variáveis
// primeiro nome
// segundo nome
// idade
// cidade
// endereço

           primeiroNome; segundoNome; cidade; endereco caractere
           idade; inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


Fimalgoritmo